# Reference: https://build-cpp.github.io/cmkr/cmake-toml
# to build:
# > cmake -B build
# > cmake --build build --config Release
[project]
name = "CSharpAPIProject"
languages = ["CXX", "C", "CSharp"]
cmake-after = """
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MP")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP")
set(CMAKE_CSharp_FLAGS "${CMAKE_CSHARP_FLAGS} /langversion:latest /platform:x64")

# Disable exceptions
# string(REGEX REPLACE "/EHsc" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

set(ASMJIT_STATIC ON CACHE BOOL "" FORCE)
set(DYNAMIC_LOADER ON CACHE BOOL "" FORCE) # OpenXR
set(BUILD_TOOLS OFF CACHE BOOL "" FORCE) # DirectXTK

if ("${CMAKE_BUILD_TYPE}" MATCHES "Release")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MT")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MT")

    # Statically compile runtime
    string(REGEX REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
    
    message(NOTICE "Building in Release mode")
endif()

set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

set(NUGET_PACKAGES_DIR "$ENV{NUGET_PACKAGES}")

# If NUGET_PACKAGES_DIR is not set, fall back to the default location
if(NOT NUGET_PACKAGES_DIR)
    if(WIN32)
        set(DEFAULT_NUGET_PATH "$ENV{USERPROFILE}/.nuget/packages")
    else()
        set(DEFAULT_NUGET_PATH "$ENV{HOME}/.nuget/packages")
    endif()
    set(NUGET_PACKAGES_DIR ${DEFAULT_NUGET_PATH})
endif()

# Helper function for setting target properties with custom DLLs
function(set_dotnet_references TARGET DLL_PREFIX DLLS)
  foreach(dll IN ITEMS ${DLLS})
    string(REPLACE "REFramework.NET." "" DLL_NAME ${dll})
    string(REPLACE ".dll" "" DLL_NAME ${DLL_NAME})
    set_target_properties(${TARGET} PROPERTIES
      VS_DOTNET_REFERENCE_${DLL_NAME}
      "${CMAKE_BINARY_DIR}/bin/${DLL_PREFIX}/REFramework.NET.${DLL_NAME}.dll"
    )
    set_target_properties(${TARGET} PROPERTIES
      VS_PACKAGE_REFERENCES "REFramework.NET.${DLL_NAME}"
    )
  endforeach()

  set_target_properties(${TARGET} PROPERTIES
    VS_DOTNET_REFERENCE_REFramework.NET
    "${REFRAMEWORK_DOT_NET_ASSEMBLY_PATH}"
	)
endfunction()

# Helper function for checking custom DLL existence
function(check_dlls_exist DLL_PREFIX DLLS VAR_NAME)
  message(STATUS "${VAR_NAME} Checking for DLLs in ${CMAKE_BINARY_DIR}/bin/${DLL_PREFIX}")
  set(${VAR_NAME} TRUE PARENT_SCOPE)
  foreach(dll IN ITEMS ${DLLS})
    if(NOT EXISTS "${CMAKE_BINARY_DIR}/bin/${DLL_PREFIX}/${dll}")
      set(${VAR_NAME} FALSE)
      message(STATUS "DLL ${dll} does not exist in ${CMAKE_BINARY_DIR}/bin/${DLL_PREFIX}")
      break()
    endif()
  endforeach()

  if (NOT ${${VAR_NAME}})
    set(${VAR_NAME} FALSE PARENT_SCOPE)
    message(STATUS "One or more specified DLLs do not exist (${DLL_PREFIX})")
  else()
    message(STATUS "All specified DLLs exist (${DLL_PREFIX})")
  endif()
endfunction()

# RE2
set(RE2_DLLS "REFramework.NET._mscorlib.dll;REFramework.NET._System.dll;REFramework.NET._System.Core.dll;REFramework.NET.application.dll;REFramework.NET.viacore.dll")
check_dlls_exist("re2" "${RE2_DLLS}" "REFRAMEWORK_REF_ASSEMBLIES_EXIST_RE2")

# RE4
set(RE4_DLLS "REFramework.NET._mscorlib.dll;REFramework.NET._System.dll;REFramework.NET._System.Core.dll;REFramework.NET.application.dll;REFramework.NET.viacore.dll")
check_dlls_exist("re4" "${RE4_DLLS}" "REFRAMEWORK_REF_ASSEMBLIES_EXIST_RE4")

# DMC5
set(DMC5_DLLS "REFramework.NET._mscorlib.dll;REFramework.NET._System.dll;REFramework.NET._System.Core.dll;REFramework.NET.application.dll;REFramework.NET.viacore.dll")
check_dlls_exist("dmc5" "${DMC5_DLLS}" "REFRAMEWORK_REF_ASSEMBLIES_EXIST_DMC5")

# DD2
set(DD2_DLLS "REFramework.NET._System.dll;REFramework.NET.application.dll;REFramework.NET.viacore.dll")
check_dlls_exist("dd2" "${DD2_DLLS}" "REFRAMEWORK_REF_ASSEMBLIES_EXIST_DD2")



# Define a list of NuGet packages and their versions
# the last part, the package framework will only be used for copying the files
set(REFRAMEWORK_NUGET_PACKAGES
    "Microsoft.CodeAnalysis.Common:4.9.2:net7.0"
    "Microsoft.CodeAnalysis.CSharp:4.9.2:net7.0"
    "ImGui.NET:1.90.1.1:net6.0"
)

# Generate the VS_PACKAGE_REFERENCES property value
set(REFRAMEWORK_PACKAGE_REFERENCES "")
foreach(PACKAGE ${REFRAMEWORK_NUGET_PACKAGES})
    # Extract package name and version from the package string
    string(REPLACE ":" ";" PACKAGE_PARTS ${PACKAGE})
    list(GET PACKAGE_PARTS 0 PACKAGE_NAME)
    list(GET PACKAGE_PARTS 1 PACKAGE_VERSION)

    # Append the package reference to the REFRAMEWORK_PACKAGE_REFERENCES variable
    set(REFRAMEWORK_PACKAGE_REFERENCES "${REFRAMEWORK_PACKAGE_REFERENCES}${PACKAGE_NAME}_${PACKAGE_VERSION};")
endforeach()
"""

[conditions]
build-csharp-test-dd2 = "REFRAMEWORK_REF_ASSEMBLIES_EXIST_DD2"
build-csharp-test-re2 = "REFRAMEWORK_REF_ASSEMBLIES_EXIST_RE2"
build-csharp-test-re4 = "REFRAMEWORK_REF_ASSEMBLIES_EXIST_RE4"

[template.CSharpSharedTarget]
type = "shared"

[template.CSharpSharedTarget.properties]
RUNTIME_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/bin/"
RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/bin"
RUNTIME_OUTPUT_DIRECTORY_DEBUG = "${CMAKE_BINARY_DIR}/bin"
LIBRARY_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib"
LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/lib"
LIBRARY_OUTPUT_DIRECTORY_DEBUG = "${CMAKE_BINARY_DIR}/lib"
DOTNET_SDK = "Microsoft.NET.Sdk"
DOTNET_TARGET_FRAMEWORK = "net8.0-windows"
VS_CONFIGURATION_TYPE = "ClassLibrary"

# REFCoreDeps is a shared target that is used by the CSharpAPI and AssemblyGenerator targets
# Mainly because adding nuget packages to C++/CLI causes random problems
# Like compiling randomly failing, so we should keep all external nuget packages
# in an actual C# project
# It also contains other stuff like the C# compiler wrapper.
[target.REFCoreDeps]
type = "CSharpSharedTarget"
sources = ["REFCoreDeps/**.cs"]

# Not using .properties here because it overrides the template properties for whatever reason
cmake-after = """
set_target_properties(REFCoreDeps PROPERTIES VS_PACKAGE_REFERENCES "${REFRAMEWORK_PACKAGE_REFERENCES}")
"""

[target.csharp-api]
type = "shared"
include-directories = ["../include/"]
sources = ["REFrameworkNET/**.cpp", "REFrameworkNET/**.c"]
headers = ["REFrameworkNET/**.hpp", "REFrameworkNET/**.h"]
compile-features = ["cxx_std_20"]
compile-options = ["/EHa", "/MD", "/doc"]
link-libraries = [
    "REFCoreDeps"
]
cmake-after = """
foreach(PACKAGE ${REFRAMEWORK_NUGET_PACKAGES})
    # Extract package name and version from the package string
    string(REPLACE ":" ";" PACKAGE_PARTS ${PACKAGE})
    list(GET PACKAGE_PARTS 0 PACKAGE_NAME)
    list(GET PACKAGE_PARTS 1 PACKAGE_VERSION)
    list(GET PACKAGE_PARTS 2 PACKAGE_FRAMEWORK)

    # Copy the package files to the output directory
    add_custom_command(
        TARGET csharp-api POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_directory
                ${NUGET_PACKAGES_DIR}/${PACKAGE_NAME}/${PACKAGE_VERSION}/lib/${PACKAGE_FRAMEWORK}
                ${CMAKE_BINARY_DIR}/bin/
        COMMENT "Copying ${PACKAGE_NAME} NuGet package"
    )
endforeach()

set(REFRAMEWORK_DOT_NET_ASSEMBLY_DIR "${CMAKE_BINARY_DIR}/bin")
set(REFRAMEWORK_DOT_NET_ASSEMBLY_PATH "${CMAKE_BINARY_DIR}/bin/REFramework.NET.dll")

set_target_properties(csharp-api PROPERTIES
VS_DOTNET_REFERENCE_REFCoreDeps
"${REFRAMEWORK_DOT_NET_ASSEMBLY_DIR}/REFCoreDeps.dll"
)

set_target_properties(csharp-api PROPERTIES VS_PACKAGE_REFERENCES "REFCoreDeps")
"""

[target.csharp-api.properties]
OUTPUT_NAME = "REFramework.NET"
RUNTIME_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/bin/"
RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/bin/"
RUNTIME_OUTPUT_DIRECTORY_DEBUG = "${CMAKE_BINARY_DIR}/bin/"
LIBRARY_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib/"
LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/lib/"
LIBRARY_OUTPUT_DIRECTORY_DEBUG = "${CMAKE_BINARY_DIR}/lib/"
COMMON_LANGUAGE_RUNTIME = "netcore"
DOTNET_TARGET_FRAMEWORK = "net8.0-windows"
# DOTNET_TARGET_FRAMEWORK_VERSION = "net8.0"
VS_GLOBAL_EnableManagedPackageReferenceSupport = "true"
# VS_PACKAGE_REFERENCES = "Microsoft.CodeAnalysis_4.9.2"
VS_GLOBAL_ConcurrentGarbageCollection = "true"

[target.AssemblyGenerator]
type = "CSharpSharedTarget"
sources = ["AssemblyGenerator/**.cs"]
link-libraries = [
    "csharp-api",
    "REFCoreDeps"
]
cmake-after = """
set_target_properties(AssemblyGenerator PROPERTIES
VS_DOTNET_REFERENCE_REFramework.NET
"${REFRAMEWORK_DOT_NET_ASSEMBLY_PATH}"
)
"""

[target.CSharpAPITest]
condition = "build-csharp-test-dd2"
type = "CSharpSharedTarget"
sources = ["test/Test/Test.cs"]
link-libraries = ["csharp-api"]
cmake-after = """
set_dotnet_references(CSharpAPITest "dd2" "${DD2_DLLS}")
"""

[target.CSharpAPITestRE2]
condition = "build-csharp-test-re2"
type = "CSharpSharedTarget"
sources = ["test/Test/TestRE2.cs"]
link-libraries = ["csharp-api"]
cmake-after = """
set_dotnet_references(CSharpAPITestRE2 "re2" "${RE2_DLLS}")
"""

[target.CSharpAPITestRE4]
condition = "build-csharp-test-re4"
type = "CSharpSharedTarget"
sources = ["test/Test/TestRE4.cs"]
link-libraries = ["csharp-api"]
cmake-after = """
set_dotnet_references(CSharpAPITestRE4 "re4" "${RE4_DLLS}")
"""

[target.ObjectExplorer]
condition = "build-csharp-test-re2"
type = "CSharpSharedTarget"
sources = ["test/Test/ObjectExplorer.cs"]
link-libraries = ["csharp-api"]
cmake-after = """
set_dotnet_references(ObjectExplorer "re2" "${RE2_DLLS}")
"""
